# .yarnrc.yml
# alternatively, remove the next two lines, PnP strict is the default
nodeLinker: "pnp"
pnpMode: "strict"

packageExtensions:
  orval@*:
    dependencies:
      lodash: "*"
  "@orval/core@*":
    dependencies:
      lodash: "*"
